---
- job_template: osp-infrastructure
  success_nodes:
  - inventory_source: REPLACEME
    success_nodes:
    - job_template: osp-dns-install
      success_nodes:
    - job_template: osp-openshift-install
      success_nodes:
      - job_template: create_httpd_file
        success_nodes:
        - job_template: redhat-access-insights-client
          success_nodes:
          - job_template: osp-openshift-cfme-ocp-provider
            success_nodes:
            - inventory_source: ONEMORETIME
              success_nodes:
              - job_template: osp-openshift-cfme-install
