:gitroot: https://github.com/openshift

== IDM Service for OpenStack with Heat

This repository defines a simple IDM service within an
OpenStack Heat stack.  The goal is to de-mystify IDM services and
deployments for low level delegated sub-domains.

The service consists of Red Hat Identity Management in a master configuration set up
with dynamic updates defined in RFC 2136.

== Requirements

* Ansible
* bind-utils
* Openstack Clients
    - python-openstackclient
    - python-heatclient
    - python-novaclient
    - python-neutronclient
    - python-cinderclient
    - python-glanceclient
    - python-swiftclient
* python2-shade

== Deployment Procedure

The stack is deployed using an Ansible playbook. Internally, Heat
creates the VMs, networks, etc. and Ansible then installs and
configures the packages.

=== Get the GIT repository

.Clone the Heat and Ansible repositories

[subs=attributes]
----
git clone {gitroot}/openshift-ansible-contrib.git
cd openshift-ansible-contrib/reference-architecture/osp-idm
----

=== Input Values

=== OpenStack Auth File

To connect to your OpenStack environment using os-client, we need create a file like bellow

.Auth File
[subs=attributes]
----
clouds:
  devstack:
    auth:
      auth_url: http://OSP_KEYSTONE_ADDR:5000/v2.0
      password: your_osp_user_password
      project_name: your_osp_project_name
      username: your_osp_user_name
    auth_type: password
----

The auth.yaml is an example, this file is on the osp-idm directory.

Or you can export the variable `OS_CLIENT_CONFIG_FILE` with the auth.yaml file

Example: `export OS_CLIENT_CONFIG_FILE=/root/auth.yaml`

=== Ansible Input File

To deploy the IDM service, you need to provide some values first.
Create a `vars.yaml` file. This file will be passed to Ansible
later on.

See `vars.sample.yaml` for an example configuration.


==== Required Values

CONFIG_FILE::
  File with information about your connection to OpenStack or you can export this variable before run the playbook +
  Type: string +
  Example: `<path_to_your_auth_file>`

EXTERNAL_NETWORK::
  The name of an existing Neutron network in the OSP environment which
  allows inbound and outbound traffic. +
  Type: string +
  Example: `public`

IMAGE::
  The name of a Glance image that will be used to for the DNS virtual
  machines. +
  Type: string +
  Example: `rhel73`

FLAVOR::

  The OpenStack Nova flavor the VMs will use +
  Type: string +
  Default: `m1.small`

SSH_USER::

  The username you can SSH as into the deployed VMs. This depends on
  the `image` you're using. For RHEL, it's `cloud-user`, for CentOS
  it's `centos`, for Fedora it's `fedora`. +
  Type: string +
  Example: `cloud-user`

SSH_KEY_NAME::
  The name of an existing Nova keypair +
  Type: string +
  Example: `ocp_key`

==== Optional Values

STACK_NAME::
  The name of the Heat stack +
  Type: string +
  Default: `dns-service`

CONTACT::

  The email address that will serve in the DNS' contact for the given
  zone/domain. +
  Type: string +
  Default: `admin@ocp3.example.com`

IDM_ADMIN_PASSWORD::

  The password that will setting  in the IDM' +
  Type: string +
  Default: `redhat@123`


==== Optional Values for Red Hat Enterprise Linux Images

The following values are all optional and only useful if your guest
images use Red Hat Enterprise Linux. They are used to register your
VMs with RHN.

RHN_USERNAME::
  Type: string +
  Default: `None`

RHN_PASSWORD::
  Type: string +
  Default: `None`

RHN_POOL::
  Type: string +
  Default: `None`


== Deploying the DNS service

The deployment uses the `vars.yaml` configuration file created in the
previous section.

The authentication variables for talking to the OpenStack services
(e.g. `OS_USERNAME` and `OS_AUTH_URL`) must be loaded (so running
`openstack stack list` succeeds).

The variable
Ansible must also be aware of the private SSH key for connecting to
the deployed VMs. The key should either be in a default location such
as `~/.ssh/id_rsa`, passed to the Ansible invocation via
`--private-key=path/to/key` or added to the SSH agent vith `ssh-add
path/to/key`.

NOTE: If you plan to delete and re-create the VMs multiple times (e.g.
  for testing or development) you may want to `export
  ANSIBLE_HOST_KEY_CHECKING=False` or prune your `~/.ssh/known_hosts`
  regularly. Otherwise SSH will fail if two VMs from different runs
  happen to receive the same IP address.

----
$ ansible-playbook deploy-idm.yaml -e @vars.yaml
----

The playbook takes three distinct actions:

1. Create a heat stack with network connectivity and instances created
and named to specification
1. Query the instances for hostname and IP address and create an inventory for Ansible
1. Install the packages and configure the IDM service
