---
- hosts: localhost
  gather_facts: false
  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
  tasks:
    - name: debug config_file
      debug: msg="{{ config_file }}"

    - name: check if config_file exists
      stat: path="{{ config_file }}"
      register: st

    - name: include config_file if exists
      include_vars: "{{ config_file }}"
      when: st.stat.exists and st.stat.isreg

    - name: cat config_file
      command: cat "{{ config_file }}"

    - name: "Print out clouds variable"
      debug: msg="{{ clouds|default('No clouds found') }}"

    - name: print out auth credentials
      debug: msg="openstack --os-auth-url '{{ clouds.devstack.auth.auth_url }}'  --os-password '{{ clouds.devstack.auth.password }}' --os-project-name '{{ clouds.devstack.auth.project_name}}'  --os-username '{{ clouds.devstack.auth.username }}' server list"

    - name: server list
      command:  openstack --os-auth-url '{{ clouds.devstack.auth.auth_url }}'  --os-password  '{{ clouds.devstack.auth.password }}' --os-project-name '{{ clouds.devstack.auth.project_name}}'  --os-username '{{ clouds.devstack.auth.username }}' server list

#    - name: test using environment variables
#      action: command
#        openstack --os-auth-url '{{ clouds.devstack.auth.auth_url }}'
#        --os-password  '{{ clouds.devstack.auth.password }}'
#        --os-project-name '{{ clouds.devstack.auth.project_name}}'
#        --os-username '{{ clouds.devstack.auth.username }}'
#        server list




#"devstack": {
#            "auth": {
#                "username": "mamorim@redhat.com",
#                "password": "KkX-vXJ-kmg-7ZC",
#                "project_name": "P&D-OpenShift",
#                "auth_url": "https://keystone.openstack.dualtec.com.br:5000/v2.0"
#            }
#        }