---

# Create a bind master
- hosts: idm
  become: true
  vars:
    ipa_packages:
      - ipa-server
      - ipa-server-dns
      - bind
      - bind-dyndb-ldap
      - deltarpm
      - rng-tools
    idm_hostname: idm-master
    domain_name: example.com
    idm_admin_password: redhat@123
    dns_forwarders: [10.16.36.29,10.11.5.19]
    rhn_repos:
      - rhel-7-server-rpms
      - rhel-7-server-rh-common-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-optional-rpms
  tasks:

    #TODO: enable repository
    - name: Disable all Red Hat repositories
      command:
        subscription-manager repos --disable=*
#      when: ansible_distribution == "RHEL"

    - name: Enable Red Hat repositories
      command:
        subscription-manager repos --enable={{ item }}
      with_items: "{{ rhn_repos }}"
#      when: ansible_distribution == "RHEL"

    # On RHEL7 this is python-dns.  On F25 it's python2-dns
    - name: install python DNS package
      package:
        name: python2-dns
        state: installed
      when: (ansible_distribution == "Fedora")

    - name: install python DNS package
      package:
        name: python-dns
        state: installed
      when: (ansible_distribution == "RHEL" or ansible_distribution == "CentOS")

    - name: Hard set the hostname
      hostname: name={{ idm_hostname }}.{{ domain_name }}

    - name: Add host entry
      lineinfile:
        dest=/etc/hosts
        regexp=" {{ idm_hostname }}.{{ domain_name }} "
        line="{{ ansible_eth0.ipv4.address }} {{ idm_hostname }}.{{ domain_name}}"
        owner=root
        group=root
        mode=0644

    - name: Ensure software is installed
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ ipa_packages }}"

    - name: start rngd
      service:
        name: rngd
        enabled: true
        state: started

    - name: Run the installer
      action: command
        ipa-server-install -U
        --realm {{ domain_name|upper }}
        --domain {{ domain_name }}
        -a {{ idm_admin_password }}
        -p {{ idm_admin_password }}
        --hostname={{ idm_hostname }}.{{ domain_name }}
        --ip-address={{ ansible_eth0.ipv4.address }}
        --forwarder={{ dns_forwarders }}
        --allow-zone-overlap
        --setup-dns
        --auto-reverse
        creates=/etc/ipa/default.conf

#TODO: Disable or Create rules on FirewallD
#    - name: Enable the individual rulesets for CentOS
#      firewalld:
#        service: "{{ item }}"
#        permanent: true
#        state: enabled
#        immediate: true
#      with_items:
#        - https
#        - ldaps
#        - kerberos
#        - kpasswd
#        - dns
#        - ntp
#      when: ansible_distribution != "Fedora" and ansible_os_family == "RedHat"
#  handlers:
#    - name: reload firewalld
#      command: firewall-cmd --reload
