---
#TODO: using subscription-manager to register before install packages

# Create a bind master
- hosts: all
  become: true
  vars:
    ipa_packages:
      - ipa-server
      - ipa-server-dns
      - bind
      - bind-dyndb-ldap
      - deltarpm
    idm_forwarders: 8.8.8.8
  tasks:

    - name: Subscribe to RHN and attach a pool
      redhat_subscription:
        username: "{{ rhn_username }}"
        password: "{{ rhn_password }}"
        pool: ["{{ rhn_pool }}"]
        force_register: true

    # On RHEL7 this is python-dns.  On F25 it's python2-dns
    - name: install python DNS package
      package:
        name: python2-dns
        state: installed
      when: (ansible_distribution == "Fedora")

    - name: install python DNS package
      package:
        name: python-dns
        state: installed
      when: (ansible_distribution == "RHEL" or ansible_distribution == "CentOS")

    - name: Hard set the hostname
      hostname: name={{ idm_hostname }}.{{ domain_name }}

    - name: Add host entry
      lineinfile:
        dest=/etc/hosts
        regexp=" {{ idm_hostname }}.{{ domain_name }} "
        line="{{ ansible_eth0.ipv4.address }} {{ idm_hostname }}.{{ domain_name}}"
        owner=root
        group=root
        mode=0644

    - name: Ensure software is installed
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ ipa_packages }}"

    - name: Run the installer
      action: command
        ipa-server-install -U
        --realm {{ domain_name|upper }}
        --domain {{ domain_name }}
        -a {{ idm_admin_password }}
        -p {{ idm_admin_password }}
        --hostname={{ idm_hostname }}.{{ domain_name }}
        --ip-address={{ ansible_eth0.ipv4.address }}
        --forwarder={{ idm_forwarders }}
        --allow-zone-overlap
        --setup-dns
        creates=/etc/ipa/default.conf

#    - name: Enable the individual rulesets for CentOS
#      firewalld:
#        service: "{{ item }}"
#        permanent: true
#        state: enabled
#        immediate: true
#      with_items:
#        - https
#        - ldaps
#        - kerberos
#        - kpasswd
#        - dns
#        - ntp
#      when: ansible_distribution != "Fedora" and ansible_os_family == "RedHat"
#  handlers:
#    - name: reload firewalld
#      command: firewall-cmd --reload
